# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\DataPersister\UserDataPersister:
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
            $passwordHasher: "@security.user_password_hasher"
        tags:
            - { name: "api_platform.state_processor", args: [App\Entity\User] }

    App\DataPersister\UserPhraseProgressDataPersister:
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $security: "@security.helper"
        tags:
            - {
                  name: "api_platform.state_processor", args: [App\Entity\UserPhraseProgress],
              }

    App\DataPersister\GroupDataPersister:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $security: '@security.helper'
        tags:
            - { name: 'api_platform.state_processor', args: [App\Entity\Group] }

    App\Controller\GroupJoinController:
        tags: ['controller.service_arguments']

    App\Controller\GroupLeaveController:
        tags: ['controller.service_arguments']

    App\Controller\GroupThemesProgressController:
        tags: ['controller.service_arguments']